### ISSUE TITLE
Task: Establish brach protection rules

### ISSUE THREAD

**Issue by kimit0310** [childmindresearch/MoBI_GUI#6]
### Description

Implement branch protection rules for main branch

### Tasks

- [ ] No direct pushes to main branch
- [ ] require pull request reviews
- [ ] enforce status checks
