### ISSUE TITLE
Task: Modularize data_inlet

### ISSUE THREAD

**Issue by kimit0310** [childmindresearch/MoBI_GUI#7]
### Description

Break down the DataInlet class into smaller classes or functions to enhance maintainability and scalability.

### Tasks

- [ ] Identify distinct responsibilities in the DataInlet class
- [ ] Create separate modules or classes for each identified responsibilities (start with data_handler, and plot_manager)
- [ ] Move relevant methods and attributes to new modules
- [ ] Add unit tests for the new modules
- [ ] Update data_inlet to utilize the new modules
- [ ] Document the new structure

### Freeform Notes

Right now, DataInlet performs both as the data inlet and plot creator. Should separate them out.
