### ISSUE TITLE
Task: Enhance structure for window.py

### ISSUE THREAD

**Issue by kimit0310** [childmindresearch/MoBI_GUI#8]
### Description

`window.py` needs their GUI components separated into individual classes and modules. Also, decide and implement an GUI architectural pattern (e.g., MVC or MVVM)

### Tasks

- [ ] Decide on an architectural pattern for the GUI structure
- [ ] Seperate out the GUI components into distinct classes or modules (e.g., main window, control panel, plot windows, etc)
- [ ] Implement the chosen architectural pattern
- [ ] Unit tests
- [ ] Document the new structure

### Freeform Notes

Need to look into which GUI architectural pattern would suit our purpose the best. to be updated on what we decided after a few meetings.
